# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5c25f0dc5ad050f21409aabed0f6b62775e44860458e54e6897181b235bb60e941cfd80114a0396f99d932dd362eb77cabfd2ae29993d0ee03662a053ca8e0b

test:
  secret_key_base: 2ef985ba09adc656f1d26bd8e7440b577579a63050ccddbaa4b191591287934b6a93f17207529c2d4c0afc6b47ab21d77a2157b6b35283c36ffad4623c553b6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
